### ISSUE TITLE
Decide on the tech stack

### ISSUE THREAD

**Issue by the-dagger** [JBossOutreach/visiting-card-backend#1]
Please decide on the tech stack so that we can move ahead.
cc : @techytushar @pro-panda @ShubhamRwt @ankitjain28may
Other backend folks are more than welcome to provide their views on this.

**Comment by ShubhamRwt** [comment]
What about using firebase for the backend of this project as I think most of the Android guys are comfortable with it @techytushar @pro-panda @the-dagger @ankitjain28may

**Comment by pro-panda** [comment]
+1 for Flask

**Comment by techytushar** [comment]
i would also like to go for Flask or Django

**Comment by lpranam** [comment]
+1 for Flask or Django

**Comment by Priya997** [comment]
+1 for Flask and Django
